name: Deploy Server

on:
  push:
    branches:
      - master
    paths:
      - 'src/*'
      - '.github/workflows/DeployServer.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: test workflow
        run: echo "YAY this workflow is running"
      - name: Add github username
        run: git config --global user.name 'palak1101'
      - name: Add github email
        run: git config --global user.email 'palaktiwari156@gmail.com'
      - name: add heroku remote
        run: git remote add heroku https://heroku:036c8332-e0dc-4c99-858b-4df2f082d7a3@git.heroku.com/palak-ecommerce-api.git
      - name: Fetch repo
        run: git fetch --unshallow
      - name: push to heroku remote
        run: git push heroku master --force
      